config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'

  get 'scheduling/index'

  get 'statistics/index'

  get 'knowledgebase/index'

  devise_for :users
  resources :candidates

  get 'welcome/index'
  root 'welcome#index'

  post 'pipelines' => 'pipeline#create'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
	has_attached_file :resume
	has_many :feedback
	has_one :interview
	has_many :pipeline

	before_create :add_empty_interview

	validates_attachment :resume, content_type: { 
		content_type: ["text/plain", "application/pdf", "application/msword", "application/vnd.ms-powerpoint", "application/vnd.openxmlformats-officedocument.presentationml.presentation"] 
		}
		accepts_nested_attributes_for :interview

		def add_empty_interview
			self.build_interview
		end

	end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	has_many :phase
	has_many :skill
	belongs_to :candidate
end

app/models/interview.rb
class Interview < ActiveRecord::Base
	belongs_to :user

	before_create :set_status


	def set_status
		self.status = "NOT_PROCESSED"
	end

end

app/models/phase.rb
class Phase < ActiveRecord::Base
	has_many :skill
	belongs_to :feedback
	has_many :pipeline
end

app/models/pipeline.rb
class Pipeline < ActiveRecord::Base
	belongs_to :phase
	belongs_to :candidate
	belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	belongs_to :phase
	belongs_to :feedback
end

app/models/user.rb
class User < ActiveRecord::Base

	before_save :setup_role
  has_many :interview
  has_many :pipeline
	has_and_belongs_to_many :roles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  def role?(role)
  	return !!self.roles.find_by_name(role.to_s.camelize)
  end

  # Default role is "USER"
  def setup_role 
  	if self.role_ids.empty?     
  		self.role_ids = [1] 
  	end
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @users = User.all
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
    @users = User.all
    @phases = Phase.all
    @skills =  Skill.all
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to edit_candidate_url(@candidate.id), notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
   @users = User.all
   respond_to do |format|
    if @candidate.update(candidate_params)
      format.html { redirect_to edit_candidate_url(@candidate.id), notice: 'Candidate was successfully updated.' }
      format.json { render :show, status: :ok, location: @candidate }
    else
      format.html { render :edit }
      format.json { render json: @candidate.errors, status: :unprocessable_entity }
    end
  end
end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:name, :dob, :email, :phone, :exp, :resume, interview_attributes: [:user_id, :status, :position, :phase_id, :id])
    end
  end

app/controllers/interview_controller.rb
class InterviewController < ApplicationController

	# POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to edit_candidate_url(@candidate.id), notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end
	
end

app/controllers/pipeline_controller.rb
class PipelineController < ApplicationController
	before_action :authenticate_user!

  # POST /pipelines
  # POST /pipelines.json
  def create
  	@pipeline = Pipeline.new(pipeline_params)

  	respond_to do |format|
  		if @pipeline.save
  			Thread.new do
  				UserMailer.welcome_message(@pipeline).deliver
  			end
  			format.html { redirect_to edit_candidate_url(@pipeline.candidate_id), notice: 'Candidate was successfully created.' }
  		else
  			format.html { render :new }
  		end
  	end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def pipeline_params
    	params.require(:pipeline).permit(:candidate_id, :phase_id, :status, :user_id)
    end

  end

app/controllers/scheduling_controller.rb
class SchedulingController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_user!
	
	def index
    	@candidates = Candidate.all
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def return_class(controller = nil, action = nil, class_name = "active")
		if (controller.nil? || params[:controller] == controller) && (action.nil? || params[:action] == action)
			class_name
		else
			""
		end
	end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/interview_helper.rb
module InterviewHelper
end

app/helpers/knowledgebase_helper.rb
module KnowledgebaseHelper
end

app/helpers/pipeline_helper.rb
module PipelineHelper
end

app/helpers/scheduling_helper.rb
module SchedulingHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/candidates/_form.html.erb
<%= form_for @candidate, :html => { :class => "form-horizontal candidate" } do |f| %>

<% if @candidate.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @candidate.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<div class="form-group col-md-6">
  <%= f.label :name, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <%=f.error_span(:name) %>
</div>
<div class="form-group  col-md-6" >
  <%= f.label :dob, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10 input-group">
    <%= f.date_field :dob, :class => 'form-control dateField datepicker' %>
    <span class="input-group-addon">
      <i class="fa fa-calendar"></i>
    </span>
  </div>
  <%=f.error_span(:dob) %>
</div>
<div class="form-group col-md-6">
  <%= f.label :email, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :email, :class => 'form-control' %>
  </div>
  <%=f.error_span(:email) %>
</div>
<div class="form-group col-md-6">
  <%= f.label :phone, :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :phone, :class => 'form-control' %>
  </div>
  <%=f.error_span(:phone) %>
</div>
<div class="form-group col-md-6">
  <%= f.label "Experience", :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.text_field :exp, :class => 'form-control' %>
  </div>
  <%=f.error_span(:exp) %>
</div>
<div class="form-group col-md-6">
  <%= f.label "Upload Resume", :class => 'control-label col-lg-2' %>
  <div class="col-lg-10">
    <%= f.file_field :resume %>
  </div>
  <% if @candidate.resume.present? %>
  <%= link_to @candidate.resume.original_filename, @candidate.resume.url %>
  <% end %>
</div>
<div class="gap15"></div>
<div class="form-group col-md-12">
  <div class="col-lg-10">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    candidates_path, :class => 'btn btn-default' %>
  </div>
</div>
<script type="text/javascript">
  $('.datepicker').datepicker({
    format : "yyyy-mm-dd"
  }
  );
</script>
<% end %>

app/views/candidates/edit.html.erb
<%- model_class = Candidate -%>
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">Personal Details</h2>
  </div>
  <!-- /.col-lg-12 -->
</div>



<%= render :partial => 'form' %>

<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">Interview Details</h2>

  </div>
</div>
<div class="panel panel-primary">
  <div class="panel-heading">
   Interview Report
 </div>
 <!-- /.panel-heading -->
 <div class="panel-body">
  <!-- Nav tabs -->
  <%= form_for @candidate do |f|%>
  <%= f.fields_for :interview do |itr| %>
  <% interviewDisabled = ""%>
  <% interviewNotDisabled = "disabled"%>
  <% if @candidate.interview.status != 'NOT_PROCESSED'%>
  <% interviewDisabled = "disabled"%>
  <% interviewNotDisabled = ""%>
  <%  end%>
  <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <tbody>
        <tr>
          <th>Current Status</th>
          <td><%= itr.object.status %></td>
          <td colspan="3"><div>
           <button type="submit" <%=interviewDisabled%> class="btn btn-success <%=interviewDisabled%>">Start Process</button> &nbsp;&nbsp;
           <button type="submit" <%=interviewNotDisabled%> class="btn btn-warning <%=interviewNotDisabled%>">Complete Process</button>
         </div></td>
       </tr>
       <tr>
        <th>Resume Recieved on</th>
        <td colspan="4"><%= @candidate.created_at%></td>        
      </tr>
      <tr>
        <th>Position Considered for</th>
        <td colspan="4">
         <%= itr.select(:position, options_for_select([['Consultant', 'cons'], ['Sr. Consultant', 'sr_cons'],['Principal Consultant', 'principal'],  ['Sr. Principal Consultant', 'sr_principal']]), {}, {:class => 'form-control'}) %>

       </td>        
     </tr>
   </tbody>
 </table>
</div>
<% if @candidate.interview.status == 'NOT_PROCESSED'%>
<input type="hidden" value="IN_PROGRESS" name="candidate[interview_attributes][status]">
<% elsif @candidate.interview.status == 'IN_PROGRESS'%>
<input type="hidden" value="COMPLETED" name="candidate[interview_attributes][status]">
<% end%>
<% end %>
<% end %>


<ul class="nav nav-pills">
  <% @phases.each_with_index do |phase, index|%>
  <% if index == 0 %>  
  <li class="active"><a href="#phase_<%= index%>" data-toggle="tab">
   <%= phase.name%></a>
 </li>
 <% else %>   
 <li><a href="#phase_<%= index%>" data-toggle="tab">
   <%= phase.name%></a>
 </li>
 <% end %>
 <% end %>
</ul>


<div class="tab-content">
  <br/>




  <% @phases.each_with_index do |phase, index|%>

  <% if index == 0 %>
  <div class="tab-pane fade in active" id="phase_<%= index%>">
   <%else %>
   <div class="tab-pane fade" id="phase_<%= index%>">
    <% end %>
    <div>
      <%= form_for :pipeline, url: pipelines_url do |f| %>
      <table class="table table-bordered table-striped" style="width: 400px;">
        <tbody>
          <tr>
            <th style="width: 25%; vertical-align: middle;">Assign To</th>        
            <td>
             <%= select_tag("pipeline[user_id]", options_from_collection_for_select(@users, :id, :email), {:class => 'form-control', :style => ' float: left; width: 200px; ' }) %>
             <button type="submit" class="btn btn-success" style=" float: right; ">Assign</button>         
           </td>

         </tr>
       </tbody>
     </table>
     <input type="hidden" name="pipeline[phase_id]" value="<%=phase.id %>"/>
     <input type="hidden" name="pipeline[status]" value="STARTED"/>
     <input type="hidden" name="pipeline[candidate_id]" value="<%=@candidate.id%>"/>
     <% end %>
   </div>

   <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <tbody>
        <tr>
          <th>skills</th>
          <th>Rating</th>
        </tr>

        <% phase.skill.each_with_index do |skill, index| %>

        <tr>
         <td>
          <%= skill.name %>

        </td>
        <td>
         <select class="form-control col-md-1">
           <option>1</option>
           <option>2</option>
           <option>3</option>
           <option>4</option>
           <option>5</option>
         </select>

       </td>
     </tr>

     <% end %>

   </tbody>
 </table>
<div class="row">
  
  <div class="col-md-6">
  <textarea class="form-control" placeholder="Enter feedback of candidate here"></textarea>
  </div>  

  <div class="col-md-12">

 <button type="button" class="btn btn-success pull-left" style=" float: right; margin: 5px">Approve</button>
 <button type="button" class="btn btn-warning pull-left" style=" float: right; margin: 5px">Reject</button>
 </div>
</div>
</div>  
</div>
<%end %>
</div>
  


<!-- /.panel-body -->
</div>
</div>

app/views/candidates/index.html.erb
<%- model_class = Candidate -%>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<%= link_to "+ Add Candidate",
new_candidate_path,
:class => 'btn btn-primary' %> <br/><br/>

<div class="panel panel-info">
<div class="panel-heading"> Candidates List</div>
<div class="panel-body">
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:dob) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:exp) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th>Resume</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
    <tr>
      <td><%= link_to candidate.id, candidate_path(candidate) %></td>
      <td><%= candidate.name %></td>
      <td><%= l(candidate.dob, :format => "%d-%m-%Y") %></td>
      <td><%= candidate.email %></td>
      <td><%= candidate.phone %></td>
      <td><%= candidate.exp %></td>
      <td><%= l(candidate.created_at, :format => "%e %b %Y %H:%M %p") %></td>
      <td><% if candidate.resume.present? %>
           <%= link_to candidate.resume.original_filename, candidate.resume.url %>
           <% else %>
           <%= "No Resume" %>
           <% end %>

     </td>
      <td>
        <%= link_to t('.edit', :default => "Details"),
        edit_candidate_path(candidate), :class => 'btn btn-primary ' %>
       <!-- <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        candidate_path(candidate),
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-danger' %>-->
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/candidates/new.html.erb
<%- model_class = Candidate -%>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<%= render :partial => 'form' %>

app/views/candidates/show.html.erb
<%- model_class = Candidate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @candidate.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
  <dd><%= @candidate.dob %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @candidate.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @candidate.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:exp) %>:</strong></dt>
  <dd><%= @candidate.exp %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              candidates_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_candidate_path(@candidate), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              candidate_path(@candidate),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>